language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hawley/complex-fib -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hawley/complex-fib npm run test -- --coverage

after_success:
  - docker build -t hawley/multi-client ./client
  - docker build -t hawley/multi-nginx ./nginx
  - docker build -t hawley/multi-server ./server
  - docker build -t hawley/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hawley/multi-client
  - docker push hawley/multi-nginx
  - docker push hawley/multi-server
  - docker push hawley/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-770729813978
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY