version: '2'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    api:
        depends_on: 
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker:
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
    dd-agent:
        image: datadog/agent:7
        container_name: dd-agent
        links:
            - redis
            - postgres
            - nginx
        environment:
            - DD_API_KEY=${DD_API_KEY}
            - DOCKER_CONTENT_TRUST=1
            - DD_HOSTNAME=multi-docker-host
            - DD_PROCESS_AGENT_ENABLED=true
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
            - /proc/:/host/proc/:ro